version: '3'
volumes:
  dados: 
services:
  db_project:
    image: postgres:9.6
    volumes:
      - dados:/var/lib/postgresql/data
      - ./scripts:/scripts
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_PASSWORD: 'password'
      POSTGRES_USER: 'postgres'
  
  frontend:
    image: nginx:1.13
    volumes:
      - ./web:/usr/share/nginx/html
    ports:
      - 4001:80

  app:
    image: python:3.6
    volumes:
      - ./app:/app
    working_dir: /app
    command: bash ./app.sh
    ports:
      - 8081:8080
  